server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/

spring:
  data:
    mongodb:
      host: 10.145.81.17
      port: 27017
      database: cart-db

ribbon:
  MaxAutoRetries:0
  MaxAutoRetriesNextServer:1
  OkToRetryOnAllOperations:false

feign:
  hystrix:
    enabled: false
