server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/

ribbon:
  MaxAutoRetries:0
  MaxAutoRetriesNextServer:1
  OkToRetryOnAllOperations:false

feign:
  hystrix:
    enabled: false
