server:
  port: 5001
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/

spring:
  data:
    mongodb:
      host: 10.145.81.39
      port: 27017
      database: auth-db
feign:
  hystrix:
    enabled: false
